### ISSUE TITLE
Bug: Timesheet shows entries from the month before/after

### ISSUE THREAD

**Issue by Hydrakus** [Euricom/timesheet-zone#127]
![screen shot 2015-04-30 at 15 36 48](https://cloud.githubusercontent.com/assets/5421847/7413781/cc8b21d0-ef4e-11e4-96ad-5af0e1575cce.png)

**Comment by Hydrakus** [comment]
Op het voorbeeld heb ik een timesheet kunnen genereren voor de maand mei, terwijl ik hier geen dagen op heb geboekt

**Comment by WartClaes** [comment]
Same here:

![screen shot 2015-05-04 at 10 21 35](https://cloud.githubusercontent.com/assets/636133/7450631/65940522-f247-11e4-867d-782eb3528f60.png)

**Comment by FredBouillon** [comment]
Fixed
