### ISSUE TITLE
Client Detail: default values

### ISSUE THREAD

**Issue by wvanhoye** [Euricom/timesheet-zone#25]
Country = Belgium
Overtime after = 10
Overtime after % = 150
Overtime saturday % = 150 
Overtime sunday % = 200

**Comment by hannesholst** [comment]
Updated model/test & seed with overtime default values

**Comment by hannesholst** [comment]
Need to review validation when default country is set to Belgium.
Should an address be complete or is it ok when only the country is set?

**Comment by wvanhoye** [comment]
Adres moet niet volledig zijn
