### ISSUE TITLE
Contract Detail:  Approver

### ISSUE THREAD

**Issue by wvanhoye** [Euricom/timesheet-zone#27]
Default waarde voor Timesheet approver name en Timesheet approver email is contactgegevens client

**Comment by wvanhoye** [comment]
Werk nog niet

**Comment by wvanhoye** [comment]
Werkt nog niet

**Comment by FredBouillon** [comment]
Fixed!

**Comment by wvanhoye** [comment]
je zou verwachten dat deze velden worden ingevuld, na het kiezen van de klant. Nu gebeurt het pas bij het saven

**Comment by FredBouillon** [comment]
Klopt. 
Is toegevoegd nu.
