### ISSUE TITLE
Time Entries: Task name

### ISSUE THREAD

**Issue by wvanhoye** [Euricom/timesheet-zone#46]
Als de task van het contract hernoemt wordt, worden de timeentries niet mee hernoemd.
Misschien by design ?

**Comment by WartClaes** [comment]
Dit is zo geïmplementeerd op aanraden van Peter. Op deze manier gaan er geen bizarre zaken gebeuren voor de gebruikers die de time sheets invullen. 

Het idee is dat het verwarrend gaat zijn als bv ik op deze week iets invul onder taak 'ABC'. Als ik dan binnen 3 weken mijn timesheet moet genereren, kan het zijn dat ik de taak die ik toen gekozen had er niet meer blijkt tussen te staan.

**Comment by cosemansp** [comment]
Mogelijke uitbreiding is dat indien de timesheet nog niet is goedgekeurd de namen wel veranderen. Maar na het goedkeuren van de timesheets moeten de namen hetzelfde blijven andere wordt een historische timescheet iets anders indien een taak hernoemt wordt. Maar dit wordt dan wel een stuk extra implementation. Te beslissen of je dit wel wilt.
