### ISSUE TITLE
Time Entries: Taak heeft nog geen unieke label

### ISSUE THREAD

**Issue by wvanhoye** [Euricom/timesheet-zone#50]
Momenteel is het 

Klant - Contract Naam

Dit is niet uniek want je kan bijvoorbeeld

Euricom - Interne zaken (- Presales)
Euricom - Interne zaken (- Coaching)
Euricom - Interne zaken (- Exam)

Klant - Taak is niet uniek, want dit kan ook

Euricom - (Timesheet Zone -) Coaching
Euricom - (Interne Zaken -) Coaching
 
Misschien iets proberen met zowel klant, contract als taak naam op 2 lijnen ?

**Comment by WartClaes** [comment]
Fixed
