### ISSUE TITLE
Date format gelijk zetten

### ISSUE THREAD

**Issue by wvanhoye** [Euricom/timesheet-zone#87]
Leaves overview:
![image](https://cloud.githubusercontent.com/assets/11091988/7275037/e214ad1c-e901-11e4-8942-12c4f92a7024.png)

Account Holidays:
![image](https://cloud.githubusercontent.com/assets/11091988/7275066/0bafa532-e902-11e4-9900-233ed1d04cbf.png)

Contracten:
![image](https://cloud.githubusercontent.com/assets/11091988/7275083/1fd53522-e902-11e4-8c8d-3017c8c19f9e.png)

User:
![image](https://cloud.githubusercontent.com/assets/11091988/7275097/31d35a7e-e902-11e4-954a-bf49fbdcadbe.png)

Timesheet:
![image](https://cloud.githubusercontent.com/assets/11091988/7275119/482c0e92-e902-11e4-9a62-0bd97a8f5ad6.png)

Time entries:

![image](https://cloud.githubusercontent.com/assets/11091988/7275140/5ff9b3b2-e902-11e4-988f-ee016e04d826.png)

**Comment by Hydrakus** [comment]
Done
